### ISSUE TITLE
dir ~/workspace is owned by root in the VM which may cause issues

### ISSUE THREAD

**Issue by LonerVamp** [andrewkrug/securing-the-cloud-supplemental#14]
In the lab VM that is provided, the Workspace folder is owned by root and other users can't readily use it. In some of your lab examples/demos, you use the ~/workspace folder, and if someone using the VM follows instructions very literally, they may run into trouble.

A student may first hit the snag when doing a git clone of the labs repo into ~/workspace, and may not think twice about just running it as sudo. But, in lab 01-03 when working with a python virtual env and the cdk, things get gummed up with the permissions not being very open and powering through with sudo won't save it.

This really isn't a big deal, nor worth redeploying the VM over. But one could maybe make mention to sudo rmdir ~/workspace and just avoid any issues, or just note the potential problem for future students who run into it.

**Comment by WesleySoftware** [comment]
> In the lab VM that is provided, the Workspace folder is owned by root and other users can't readily use it. In some of your lab examples/demos, you use the ~/workspace folder, and if someone using the VM follows instructions very literally, they may run into trouble.
> 
> A student may first hit the snag when doing a git clone of the labs repo into ~/workspace, and may not think twice about just running it as sudo. But, in lab 01-03 when working with a python virtual env and the cdk, things get gummed up with the permissions not being very open and powering through with sudo won't save it.
> 
> This really isn't a big deal, nor worth redeploying the VM over. But one could maybe make mention to sudo rmdir ~/workspace and just avoid any issues, or just note the potential problem for future students who run into it.

I am working on a replacement VM, I am just running into some friction with it because I want to make sure it works alright with VMWare, VirtualBox, and KVM without much further tweaking. I also want to go through the labs again with it as a test, so it will take a while.

If anyone wants to copypasta the solution though, blindly copy and run the following in your terminal:
```
sudo chown -R vagrant:vagrant /home/vagrant/workspace
```

**Comment by andrewkrug** [comment]
@WesleySoftware the packer file that builds the vm is in this repo: https://github.com/andrewkrug/packer-securing-the-cloud

Should be a quick fix for me to address.  Thank you to both of you for reporting.

**Comment by andrewkrug** [comment]
This has been fixed in the latest version of the course vm.
